version: 2

formats:
    - pdf

sphinx:
    configuration: source/conf.py

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"

python:
    install:
      - requirements: source/requirements.txt
